import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  footer: {
    position: "absolute",
    bottom: 10,
    width: "100%",
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    paddingHorizontal: 20,
  },
  no_contact_text: {
    color: "cadetblue",
    textAlign: "center",
    fontSize: 25,
    marginTop: 100,
  },
  iconContainer: {
    height: 50,
    width: 50,
    backgroundColor: "cadetblue",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  iconContainer2: {
    height: 50,
    width: 50,
    backgroundColor: "cadetblue",
    borderRadius: 25,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 15,
  },
  header: {
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 50,
  },
  header_for_searching: {
    padding: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 50,
  },
  divider: {
    borderColor: "cadetblue",
    borderWidth: 1,
    marginBottom: 3,
    marginTop: 3,
  },
  delete_button: { flexDirection: "row", alignItems: "center" },
  inputContainer: {
    height: 40,
    width: "80%",
    padding: 5,
    backgroundColor: "#ffffff",
    borderRadius: 30,
    borderColor: "cadetblue",
    borderWidth: 1,
  },
  form_button_text: {
    color: "white",
    fontSize: 18,
  },
  form_button: {
    height: 40,
    width: "70%",
    marginVertical: 15,
    backgroundColor: "cadetblue",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 30,
    marginTop: 15,
  },
  not_verify: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
  },
  not_verify_text: { color: "black", textAlign: "center", fontSize: 25 },
  not_verify_welcome_text: {
    color: "cadetblue",
    textAlign: "center",
    fontSize: 45,
    fontWeight: "bold",
    marginBottom: 30,
  },
});
